### ISSUE TITLE
Some missing files

### ISSUE THREAD

**Issue by nipun-das** [Bheemm1992/E-Commerce-#3]
Hey, I forked your project and can't seem to run it due to the following issues:

The project doesn't follow the correct folder structure for a maven project.
There is no pom.xml or application.properties file. 

Ensure you have it like this:

SpringEcom/                      # Main project directory
├── src/                         # Source folder
│   ├── main/
│   │   ├── java/                # Java source code directory
│   │   │   └── com/yourcompany/ecommerce/  # Package name directory
│   │   │       ├── controller/  # Controller package
│   │   │       │   └── ProductController.java  # Handles product-related requests
│   │   │       ├── model/       # Model package
│   │   │       │   └── Product.java       # Product entity class
│   │   │       ├── repo/        # Repository package
│   │   │       │   └── ProductRepo.java   # Repository interface for product data
│   │   │       └── service/     # Service package
│   │   │           └── ProductService.java # Service class for product operations
│   │   └── resources/           # Resources like application.properties
│   │       └── application.properties # Configuration file
│   └── test/                    # Unit and integration tests
│       └── java/                # Test source code
│           └── com/yourcompany/ecommerce/
│               └── ProductServiceTest.java  # Test class for service layer
├── pom.xml                      # Maven project configuration file
├── README.md                    # Project documentation

**Comment by AlexLoni1992** [comment]
thanks for your concern, as we can see there is no pom.xml file
We will add it sooner
